### ISSUE TITLE
UR-H #37: User should be able to reorder habits on their habit list

### ISSUE THREAD

**Issue by MacMalainey** [CMPUT301F21T09/BudgetProjectName#100]
Risk: Low
Story Points: 5

User Stories: US 01.08.02

**Comment by AtrazineC** [comment]
We've decided to axe this requirement since our UI wasn't designed around this feature and getting this to work would require too much effort. The "easiest" solution we thought of, however, would be to 
- add a "reorder habits" button somewhere which shows a list of all the user's habits (not that hard), 
- creating a scrollable list that allows users to drag and drop habits to reorder them (really hard), and 
- make habits stored in a doubly linked list in our database (the UserModel would point to the "head" of the linked list, and each node contains the previous and next habit) (also really hard, would have to deal with a bunch of edge cases like if the user removes the habit that is the head of the linked list. We'd also have to possibly clear existing data, or put in the work to convert existing habits into a linked list).
